#!/bin/sh

# check internet connection
nc -G 5 -z 1.1.1.1 80 &>/dev/null
if [[ $? -eq 0 ]]; then

# Variables
INVESTMENT=40800 # euro
LIABILITY=10000 # xtz

WALLET_ADDRESS='tz1VjYmQHw4QE6tYTQLLfWNjqkUNwMC7YPoF'
OVEN_ADDRESS='KT1AKcRY2F8uZv5psx2gUm7AoTk8Cp6ei4hM'

# Price
PRICE=$(curl -sX 'GET' 'https://api.coingecko.com/api/v3/simple/price?ids=tezos&vs_currencies=eur' -H 'accept: application/json')

EUR=$(echo $PRICE | jq --raw-output '.tezos.eur')

# Wallet
WALLET=$(curl -sX GET "https://api.tzkt.io/v1/accounts/$WALLET_ADDRESS")
XTZ=$(echo $WALLET | jq --raw-output '.balance')

# Oven
OVEN=$(curl -sX GET "https://api.tzkt.io/v1/contracts/$OVEN_ADDRESS")
OVEN_XTZ=$(echo $OVEN | jq --raw-output '.balance')

# Status
python3 -c "\
value=($XTZ+$OVEN_XTZ)/10**6*$EUR
print(f'ꜩ : {$EUR:,.2f} €')"

echo "---"
echo "Wallet"

python3 -c "\
print(f'Tezos: {$XTZ/10**6:,.2f} ꜩ')"

python3 -c "\
value=$XTZ/10**6*$EUR
print(f'Value: {value:,.2f} €')"

echo "---"
echo "Oven"

python3 -c "\
print(f'Tezos: {$OVEN_XTZ/10**6:,.2f} ꜩ')"

python3 -c "\
value=$OVEN_XTZ/10**6*$EUR
print(f'Value: {value:,.2f} €')"

echo "---"
echo "Investment"

python3 -c "\
print(f'Bought: {$INVESTMENT:,.2f} €')"

python3 -c "\
value=($XTZ+$OVEN_XTZ-($LIABILITY*10**6))/10**6*$EUR
print(f'Value: {value:,.2f} €')"

python3 -c "\
value=($XTZ+$OVEN_XTZ-($LIABILITY*10**6))/10**6*$EUR
diff=value-$INVESTMENT
print(f'{\"Profit\" if diff >= 0 else \"Loss\"}: {diff:,.2f} €')"

python3 -c "\
value=($XTZ+$OVEN_XTZ-($LIABILITY*10**6))/10**6*$EUR
diff=value-$INVESTMENT
percentage=diff*100/$INVESTMENT
print(f'Percentage: {percentage:,.2f} %')"

else

echo "ꜩ : --- €"

fi
