brew install --cask android-studio
brew install --cask balenaetcher
brew install --cask discord
brew install --cask docker
brew install --cask electrum
brew install --cask flutter
brew install --cask font-jetbrains-mono
brew install --cask free-gpgmail
brew install --cask google-chrome
brew install --cask gpg-suite-no-mail
brew install --cask karabiner-elements
brew install --cask keepassxc
brew install --cask mactex
brew install --cask microsoft-auto-update
brew install --cask minecraft
brew install --cask obsidian
brew install --cask rar
brew install --cask rectangle
brew install --cask signal
brew install --cask spotify
brew install --cask steam
brew install --cask stremio
brew install --cask swiftbar
brew install --cask syncthing
brew install --cask tex-live-utility
brew install --cask tor-browser
brew install --cask transmission
brew install --cask virtualbox
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask wezterm
brew install --cask zoom
