brew install --cask adoptopenjdk
brew install --cask android-studio
brew install --cask bitcoin-core
brew install --cask blackhole-16ch
brew install --cask discord
brew install --cask docker
brew install --cask firefox
brew install --cask flutter
brew install --cask font-jetbrains-mono
brew install --cask google-chrome
brew install --cask gpg-suite
brew install --cask ipfs
brew install --cask karabiner-elements
brew install --cask mactex
brew install --cask microsoft-auto-update
brew install --cask microsoft-teams
brew install --cask multipass
brew install --cask neovim-nightly
brew install --cask notion
brew install --cask obs
brew install --cask signal
brew install --cask spotify
brew install --cask stremio
brew install --cask swiftbar
brew install --cask syncplay
brew install --cask tex-live-utility
brew install --cask tor-browser
brew install --cask transmission
brew install --cask virtualbox
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask zoomus
