brew install --cask adobe-creative-cloud
brew install --cask adoptopenjdk
brew install --cask android-studio
brew install --cask discord
brew install --cask docker
brew install --cask flutter
brew install --cask font-jetbrains-mono
brew install --cask google-chrome
brew install --cask gpg-suite
brew install --cask karabiner-elements
brew install --cask lastpass
brew install --cask microsoft-auto-update
brew install --cask microsoft-office
brew install --cask microsoft-teams
brew install --cask neovim-nightly
brew install --cask signal
brew install --cask slack
brew install --cask spotify
brew install --cask stremio
brew install --cask syncplay
brew install --cask transmission
brew install --cask virtualbox
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask zoomus
