brew install adwaita-icon-theme
brew install automake
brew install cask
brew install cmake
brew install cvc4
brew install deno
brew install expat
brew install fd
brew install ffmpeg
brew install gh
brew install ghostscript
brew install git
brew install gtksourceview
brew install gtksourceview3
brew install jq
brew install libxml2
brew install llvm
brew install luarocks
brew install lzlib
brew install mas
brew install nasm
brew install neovim
brew install node
brew install openjdk
brew install pandoc
brew install pypy3
brew install shellcheck
brew install texlab
brew install tree
brew install wget
brew install zsh-autosuggestions
brew install zsh-git-prompt
brew install zsh-history-substring-search
brew install zsh-you-should-use
