brew install cmake
brew install fd
brew install ffmpeg
brew install gh
brew install ghostscript
brew install git
brew install jq
brew install llvm
brew install mas
brew install nasm
brew install neovim
brew install node
brew install perl
brew install ripgrep
brew install texlab
brew install tree
brew install zsh-autosuggestions
brew install zsh-git-prompt
brew install zsh-history-substring-search
